# 処理の負荷設定: high, medium, low
# high: 最も詳細なログを収集しますが、パフォーマンスへの影響が最も大きいです。
# medium: バランスの取れた設定。
# low: パフォーマンスへの影響を最小限に抑えますが、収集されるログは少なくなります。
processing_intensity: high

# バックアップの最大保持数
# これを超える古いバックアップは自動的に削除されます。
max_backups: 5

# ログ収集時に無視するプレイヤー名やサーバーメッセージのキーワード
# ここに含まれる名前を持つプレイヤーのログは一部処理がスキップされることがあります。
ignored_names:
  - "Villager"
  - "Server"

# カスタムパターンの定義
# 特定のログファイルに対して、どの情報を抽出するかを正規表現で定義します。
custom_patterns:
  # 例: 'chat.log'ファイルから[PlayerName: Message]の形式を抽出
  chat:
    - '\\[Server thread/INFO\\]: <(?<player>.+?)> (?<message>.+)'
  # 例: 特殊なデスメッセージを抽出
  death:
    - '(?<player>.+?) fell out of the world'