name: YAPIMARU_Plugin
version: 2.5.1
main: com.yapimaru.plugin.YAPIMARU_Plugin
api-version: '1.21'
author: YAPIMARU
description: 動画撮影に便利なプラグインです。
load: STARTUP
depend: [WorldEdit]

commands:
  yapimaru:
    description: YAPIMARUプラグインの管理コマンドです。
    usage: /<command> [reload|list|cmlist]
    aliases: [ym]
    permission: yapimaru.admin
    permission-message: このコマンドを使用する権限がありません。
  hub:
    description: ハブにテレポートします。
    usage: /<command>
  skinlist:
    description: スキン名の一覧を表示します。
    usage: /<command>
    permission: yapimaru.skinlist
  timer:
    description: タイマーを管理します。
    usage: /<command> [subcommand] [args]
    aliases: [tm]
    permission: yapimaru.admin
    permission-message: このコマンドを使用する権限がありません。
  pvp:
    description: PvPモードを管理します。
    usage: /<command> [subcommand] [args]
    permission: yapimaru.admin
    permission-message: このコマンドを使用する権限がありません。
  name:
    description: 偽名と名前の色を管理します。
    usage: /<command> [subcommand] [args]
    permission: yapimaru.admin
    permission-message: このコマンドを使用する権限がありません。
  creator:
    description: 便利な管理GUIを開きます。
    usage: /<command> [subcommand] [args]
    aliases: [c]
    permission: yapimaru.creator
    permission-message: このコマンドを使用する権限がありません。
  server:
    description: サーバーの停止・再起動を管理します。
    usage: /<command> [off|restart]
    permission: yapimaru.admin
    permission-message: このコマンドを使用する権限がありません。
  spectator:
    description: スペクテイターの表示設定を管理します。
    usage: /<command> [on|off]
    permission: yapimaru.admin
    permission-message: このコマンドを使用する権限がありません。
  voting:
    description: 投票関連のコマンドです。
    usage: /<command> [question|evaluation|end|result|average|list] [args]
    aliases: [vote]
    permission: yapimaru.admin
    permission-message: このコマンドを使用する権限がありません。
  ans:
    description: 進行中の投票に回答します。
    usage: /<command> <投票ID> <番号>
  photographing:
    description: 撮影参加回数を記録します。
    usage: /<command> on
    permission: yapimaru.admin
    permission-message: このコマンドを使用する権限がありません。
  stats:
    description: 参加者の統計情報を表示します。
    usage: /<command> <player|list> [args]
    permission: yapimaru.admin
    permission-message: このコマンドを使用する権限がありません。
  # ★★★ 新しいコマンド定義を追加 ★★★
  ppparticipant:
    description: config.ymlからプレイヤーデータを個別のファイルに手動で移行します。
    usage: /<command>
    permission: yapimaru.admin
    permission-message: このコマンドを使用する権限がありません。


permissions:
  yapimaru.admin:
    description: 全ての管理コマンドへのアクセスを許可します。
    default: op
  yapimaru.skinlist:
    description: /skinlist コマンドの使用を許可します。
    default: true
  yapimaru.creator:
    description: /creator コマンドの使用を許可します。
    default: op