name: YAPIMARU_Plugin
version: '3.0.0'
main: com.yapimaru.plugin.YAPIMARU_Plugin
api-version: '1.21'
author: YAPIMARU
description: 動画撮影に便利なプラグインです。
load: STARTUP
depend: [WorldEdit]

commands:
  yapimaru:
    description: YAPIMARUプラグインの管理コマンドです。
    usage: /<command> [reload|list|cmlist|participant]
    aliases: [ym]
    permission: yapimaru.admin
  hub:
    description: ハブにテレポートします。
    usage: /<command>
  skinlist:
    description: スキン名の一覧を表示します。
    usage: /<command> [検索語]
    permission: yapimaru.skinlist
  timer:
    description: タイマーを管理します。
    usage: /<command> [subcommand] [args]
    aliases: [tm]
    permission: yapimaru.admin
  pvp:
    description: PvPモードを管理します。
    usage: /<command> [subcommand] [args]
    permission: yapimaru.admin
  name:
    description: 偽名と名前の色を管理します。
    usage: /<command> [subcommand] [args]
  creator:
    description: 便利な管理GUIを開きます。
    usage: /<command> [subcommand] [args]
    aliases: [c]
    permission: yapimaru.creator
  server:
    description: サーバーの停止・再起動を管理します。
    usage: /<command> [off|restart]
    permission: yapimaru.admin
  spectator:
    description: スペクテイターの表示設定を管理します。
    usage: /<command> [on|off]
    permission: yapimaru.admin
  voting:
    description: 投票関連のコマンドです。
    usage: /<command> [question|evaluation|end|result|average|list] [args]
    aliases: [vote]
    permission: yapimaru.admin
  ans:
    description: 進行中の投票に回答します。
    usage: /<command> <投票ID> <番号>
  stats:
    description: 統計情報を表示します。
    usage: /<command> [player|list] [args]
    permission: yapimaru.admin
  photographing:
    description: 撮影参加回数を記録します。
    usage: /<command> on
    permission: yapimaru.admin
  # ★★★ 以下の定義を修正 ★★★
  log:
    description: 古いログファイルの処理や統計のリセットを行います。（一時的機能）
    usage: /<command> <add|reset>
    permission: yapimaru.admin

permissions:
  yapimaru.admin:
    description: 全ての管理コマンドへのアクセスを許可します。
    default: op
  yapimaru.skinlist:
    description: /skinlist コマンドの使用を許可します。
    default: true
  yapimaru.creator:
    description: /c コマンドの使用を許可します。
    default: op